site_name: Veille Cyber RSSI – Département du Tarn
theme:
  name: material
nav:
  - Accueil: index.md
  - Veille: !include_dir_list_folded veille
markdown_extensions:
  - tables
plugins:
    - search
    - awesome-pages